---

language: python
dist: xenial

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

matrix:
  fast_finish: true

env:
  matrix:
    - ANSIBLE=2.4
    - ANSIBLE=2.5
    - ANSIBLE=2.6
    - ANSIBLE=2.7

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
